name: Create Release on Tag v{MAJOR}.{MINOR}.{PATCH}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger the workflow on tag push events matching the semantic versioning pattern

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} -t ${{ github.ref }} --generate-notes
