name: Terraform CI - validate

on:
  [push]

jobs:
  tf_validate:
    name: 'Terraform validate'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TERRAFORM_VERSION: 1.3.7
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Terraform - validate examples/basic'
        working-directory: examples/basic
        run: |
          terraform init
          terraform validate
