name: Terraform CI - Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'rc-*'


jobs:
  tf_integration:
    name: 'Terraform integration'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TERRAFORM_VERSION: 1.3.7
      CI_SA_EMAIL: gh-actions-tf-gcp-export@worklytics-corp.iam.gserviceaccount.com
      GCP_IDENTITY_POOL: 'projects/432357880585/locations/global/workloadIdentityPools/github-actions/providers/github'
      EXAMPLE_TENANT_SA_EMAIL: tf-gcp-export-tenant@worklytics-ci.iam.gserviceaccount.com
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUCKET_NAME: terraform-gcp-worklytics-export-ci
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - id: 'auth-gcp'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_IDENTITY_POOL }}
          service_account: ${{ env.CI_SA_EMAIL }}

      - name: 'Terraform - integration test examples/basic apply'
        id: terraform_apply
        working-directory: examples/basic
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="bucket_name=${{ env.BUCKET_NAME }}" \
            -var="worklytics_tenant_sa_email=${{ env.EXAMPLE_TENANT_SA_EMAIL }}"

      - name: 'Terraform - integration test examples/basic gcs write'
        run: |
          ./test/rsync.sh ${{ env.EXAMPLE_TENANT_SA_EMAIL }} ${{ env.BUCKET_NAME }}

      - name: 'Terraform - integration test examples/basic terraform destroy'
        if: always() # try to force this to ALWAYS happen, no matter if previous stuff failed
        working-directory: examples/basic
        run: |
          gsutil -m rm -r gs://${{ env.BUCKET_NAME }}/*
          terraform destroy -auto-approve \
            -var="bucket_name=${{ env.BUCKET_NAME }}" \
            -var="worklytics_tenant_sa_email=${{ env.EXAMPLE_TENANT_SA_EMAIL }}"
