name: Terraform CI - Lint

on:
  [push]

jobs:
  tf_lint:
    name: 'Terraform lint'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TERRAFORM_VERSION: 1.3.7
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'lint Terraform code'
        # see https://www.terraform.io/cli/commands/fmt
        run:
          terraform fmt -check -recursive -diff .
